import type { Database as SqliteClient } from "bun:sqlite";

import { assertTablesClassified, CATALOG_TABLE_NAMES } from "./tables";

/** Committed catalog seed. Text, one INSERT per line, so git can delta it. */
export const SNAPSHOT_PATH = `${import.meta.dir}/seeds/catalog.sql`;

const SNAPSHOT_HEADER = `-- Generated by \`bun run db:snapshot\`. Do not edit by hand.
--
-- Catalog tables only. See src/db/tables.ts for what that means and why
-- operational and user tables are excluded. Apply with \`bun run db:seed\`,
-- which expects the schema to already exist (\`bun run db:migrate\`).
`;

function quoteIdentifier(name: string): string {
  return `"${name.replaceAll('"', '""')}"`;
}

/**
 * bun:sqlite hands back exactly these five shapes, so anything else means the
 * schema grew a type this dump does not know how to round-trip.
 */
function quoteLiteral(value: unknown): string {
  if (value === null || value === undefined) {
    return "NULL";
  }

  if (typeof value === "string") {
    return `'${value.replaceAll("'", "''")}'`;
  }

  if (typeof value === "bigint") {
    return value.toString();
  }

  if (typeof value === "number") {
    if (!Number.isFinite(value)) {
      throw new TypeError(`Cannot serialise non-finite number: ${value}`);
    }

    return String(value);
  }

  if (value instanceof Uint8Array) {
    return `X'${Buffer.from(value).toString("hex")}'`;
  }

  throw new TypeError(`Cannot serialise ${typeof value} into a snapshot`);
}

export function listTables(client: SqliteClient): string[] {
  return client
    .query<{ name: string }, []>(
      "SELECT name FROM sqlite_master WHERE type = 'table' ORDER BY name"
    )
    .all()
    .map((row) => row.name);
}

function columnNames(client: SqliteClient, table: string): string[] {
  return client
    .query<{ name: string }, [string]>(
      "SELECT name FROM pragma_table_info(?) ORDER BY cid"
    )
    .all(table)
    .map((row) => row.name);
}

/**
 * Rows come out in a stable order so re-running the snapshot produces a
 * line-level diff rather than a reshuffled file. Primary key order is the
 * cheapest stable key; `sections` currently declares none, so it falls back to
 * ordering by every column.
 */
function orderingColumns(client: SqliteClient, table: string): string[] {
  const keyColumns = client
    .query<{ name: string }, [string]>(
      "SELECT name FROM pragma_table_info(?) WHERE pk > 0 ORDER BY pk"
    )
    .all(table)
    .map((row) => row.name);

  return keyColumns.length > 0 ? keyColumns : columnNames(client, table);
}

function dumpTable(client: SqliteClient, table: string): string[] {
  const columns = columnNames(client, table);

  if (columns.length === 0) {
    throw new Error(`Table ${table} does not exist in this database.`);
  }

  const columnList = columns.map(quoteIdentifier).join(", ");
  const orderBy = orderingColumns(client, table)
    .map(quoteIdentifier)
    .join(", ");

  const rows = client
    .query(
      `SELECT ${columnList} FROM ${quoteIdentifier(table)} ORDER BY ${orderBy}`
    )
    .values();

  const prefix = `INSERT INTO ${quoteIdentifier(table)} (${columnList}) VALUES (`;

  return rows.map((row) => `${prefix}${row.map(quoteLiteral).join(", ")});`);
}

export function createSnapshot(
  client: SqliteClient,
  tableNames: readonly string[] = CATALOG_TABLE_NAMES
): string {
  assertTablesClassified(listTables(client));

  const deletes: string[] = [];

  // Reverse dependency order, so the wipe holds up even with foreign keys on.
  for (let index = tableNames.length - 1; index >= 0; index -= 1) {
    deletes.push(`DELETE FROM ${quoteIdentifier(tableNames[index])};`);
  }

  const inserts = tableNames.flatMap((table) => {
    const statements = dumpTable(client, table);

    return [`-- ${table} (${statements.length} rows)`, ...statements, ""];
  });

  return [
    SNAPSHOT_HEADER,
    "PRAGMA foreign_keys = OFF;",
    "BEGIN TRANSACTION;",
    "",
    ...deletes,
    "",
    ...inserts,
    "COMMIT;",
    "PRAGMA foreign_keys = ON;",
    "",
  ].join("\n");
}

/**
 * The snapshot toggles `foreign_keys` around its own transaction, so callers do
 * not need to. Enforcement is off while rows load — the file is ordered, but a
 * partially applied catalog would otherwise trip references mid-load — then
 * `foreign_key_check` confirms the result is actually consistent.
 */
export function applySnapshot(client: SqliteClient, sql: string): void {
  assertTablesClassified(listTables(client));

  client.run(sql);

  const violations = client
    .query<{ table: string; rows: number }, []>(
      `SELECT "table", count(*) AS rows FROM pragma_foreign_key_check()
       GROUP BY "table" ORDER BY "table"`
    )
    .all();

  if (violations.length > 0) {
    const summary = violations
      .map((row) => `${row.table} (${row.rows})`)
      .join(", ");

    throw new Error(`Seed left foreign key violations in: ${summary}`);
  }
}
