import { getTableName } from "drizzle-orm";
import type { SQLiteTable } from "drizzle-orm/sqlite-core";

import {
  adminAuditLog,
  courseMatchingSections,
  courses,
  departments,
  importRuns,
  professorDepartments,
  professorRatingPulls,
  professorRatings,
  professors,
  sectionProfessors,
  sections,
  terms,
} from "./schema";

export type TableClassification = "catalog" | "operational" | "user";

/**
 * Deterministic importer output with no personal data in it. These are the only
 * tables `db:snapshot` is allowed to write, because the snapshot is committed.
 *
 * Declared in dependency order: the snapshot inserts in this order and deletes
 * in the reverse, so a seed still applies cleanly if foreign keys are enforced.
 */
const CATALOG: readonly SQLiteTable[] = [
  terms,
  departments,
  professors,
  professorDepartments,
  courses,
  courseMatchingSections,
  sections,
  sectionProfessors,
  professorRatings,
];

/**
 * Logs of local activity. Regenerated by using the app, meaningless on another
 * machine, and paired with locks (`getActiveRun`) that assume a single writer,
 * so they are never snapshotted and never shared between worktrees.
 *
 * `professor_rating_pulls` is here while `professor_ratings` is catalog, which
 * looks inconsistent but is not: the reviews are the data, and the pull log is
 * one machine's record of when it last asked RMP for them. Nothing is lost by
 * excluding it, because the high-water mark that drives the next pull is derived
 * from the reviews rather than read back from this table.
 */
const OPERATIONAL: readonly SQLiteTable[] = [
  importRuns,
  adminAuditLog,
  professorRatingPulls,
];

/**
 * Anything holding real people's data: accounts, sessions, Acadia credentials,
 * saved schedules. Empty today. It must stay empty of anything the snapshot
 * touches — that is the whole reason this file exists rather than a hardcoded
 * list inside the snapshot script.
 */
const USER: readonly SQLiteTable[] = [];

/**
 * Bookkeeping we neither own nor snapshot. `sqlite_%` covers the internal
 * `sqlite_sequence` / `sqlite_stat*` tables SQLite creates on its own.
 */
const INTERNAL_TABLE_NAMES: ReadonlySet<string> = new Set([
  "__drizzle_migrations",
]);

export const CATALOG_TABLE_NAMES = CATALOG.map(getTableName);
export const OPERATIONAL_TABLE_NAMES = OPERATIONAL.map(getTableName);
export const USER_TABLE_NAMES = USER.map(getTableName);

const CLASSIFICATIONS = new Map<string, TableClassification>([
  ...CATALOG_TABLE_NAMES.map(
    (name) => [name, "catalog"] as [string, TableClassification]
  ),
  ...OPERATIONAL_TABLE_NAMES.map(
    (name) => [name, "operational"] as [string, TableClassification]
  ),
  ...USER_TABLE_NAMES.map(
    (name) => [name, "user"] as [string, TableClassification]
  ),
]);

export function classifyTable(name: string): TableClassification | undefined {
  return CLASSIFICATIONS.get(name);
}

export function isInternalTable(name: string): boolean {
  return name.startsWith("sqlite_") || INTERNAL_TABLE_NAMES.has(name);
}

/** Order follows the caller's; `listTables` already sorts by name. */
export function findUnclassifiedTables(
  tableNames: readonly string[]
): string[] {
  return tableNames.filter(
    (name) => !(isInternalTable(name) || CLASSIFICATIONS.has(name))
  );
}

/**
 * Called by both snapshot scripts before they touch a database. Adding a table
 * without classifying it fails here instead of silently dumping its rows into a
 * committed seed file.
 */
export function assertTablesClassified(tableNames: readonly string[]): void {
  const unclassified = findUnclassifiedTables(tableNames);

  if (unclassified.length > 0) {
    throw new Error(
      `Unclassified table(s): ${unclassified.join(", ")}. Add each to CATALOG, OPERATIONAL, or USER in src/db/tables.ts before snapshotting or seeding.`
    );
  }
}
