CREATE TABLE `departments` (
	`prefix` text PRIMARY KEY,
	`name` text NOT NULL,
	`facultyUrl` text NOT NULL
);
--> statement-breakpoint
INSERT INTO `departments` (`prefix`, `name`, `facultyUrl`) VALUES
	('KINE', 'Kinesiology', 'https://kinesiology.acadiau.ca/faculty-staff.html'),
	('EDUC', 'Education', 'https://education.acadiau.ca/faculty-staff.html'),
	('BIOL', 'Biology', 'https://biology.acadiau.ca/faculty-staff.html'),
	('MATH', 'Mathematics and Statistics', 'https://math.acadiau.ca/faculty.html'),
	('HIST', 'History', 'https://history.acadiau.ca/Faculty/Staff.html'),
	('ENGL', 'English', 'https://english.acadiau.ca/faculty-staff.html'),
	('POLS', 'Political Science', 'https://polisci.acadiau.ca/faculty-and-staff.html'),
	('MUSI', 'Music', 'https://music.acadiau.ca/faculty.html'),
	('BUSI', 'Business Administration', 'https://business.acadiau.ca/about-us/faculty-directory.html'),
	('CHEM', 'Chemistry', 'https://chemistry.acadiau.ca/faculty-staff.html'),
	('SOCI', 'Sociology', 'https://sociology.acadiau.ca/People.html'),
	('COMP', 'Computer Science', 'https://cs.acadiau.ca/faculty-staff.html'),
	('GEOL', 'Geology', 'https://ees.acadiau.ca/faculty-staff.html'),
	('BIBL', 'Biblical Studies', 'https://acadiadiv.ca/faculty/'),
	('PSYC', 'Psychology', 'https://psychology.acadiau.ca/Faculty_and_Staff.html'),
	('PACC', 'Pastoral Care and Counselling', 'https://acadiadiv.ca/faculty/'),
	('NXGN', 'Next Generation Ministry', 'https://acadiadiv.ca/faculty/'),
	('EVAN', 'Evangelism and Mission', 'https://acadiadiv.ca/faculty/'),
	('PAST', 'Pastoral Ministry', 'https://acadiadiv.ca/faculty/'),
	('THEO', 'Theology', 'https://acadiadiv.ca/faculty/'),
	('ECON', 'Economics', 'https://economics.acadiau.ca/our-people.html'),
	('FRAN', 'French', 'https://languages.acadiau.ca/faculty-and-staff.html'),
	('LEDR', 'Leadership', 'https://acadiadiv.ca/faculty/'),
	('NUTR', 'Nutrition', 'https://nutrition.acadiau.ca/faculty-and-staff.html'),
	('CODE', 'Community Development', 'https://commdev.acadiau.ca/faculty-staff.html'),
	('CHUR', 'Church History', 'https://acadiadiv.ca/faculty/'),
	('DISP', 'Discipleship', 'https://acadiadiv.ca/faculty/'),
	('APSC', 'Applied Science', 'https://engineering.acadiau.ca/faculty-and-staff.html'),
	('DMIN', 'Ministry', 'https://acadiadiv.ca/faculty/'),
	('PHYS', 'Physics', 'https://physics.acadiau.ca/people.html'),
	('PHIL', 'Philosophy', 'https://philosophy.acadiau.ca/facstaff.html'),
	('IDST', 'Interdisciplinary Studies', 'https://arts.acadiau.ca/international-development-studies.html'),
	('SPFM', 'Spiritual Formation', 'https://acadiadiv.ca/faculty/'),
	('CLAS', 'Classics', 'https://history.acadiau.ca/Faculty/Staff.html'),
	('THEA', 'Theatre', 'https://theatre.acadiau.ca/faculty-staff.html'),
	('GREE', 'Greek', 'https://history.acadiau.ca/Faculty/Staff.html'),
	('NURS', 'Nursing', 'https://nursing.acadiau.ca/faculty-staff.html'),
	('ART', 'Art', 'https://arts.acadiau.ca/art-courses/faculty.html'),
	('GERM', 'German', 'https://languages.acadiau.ca/faculty-and-staff.html'),
	('CHAP', 'Chaplaincy', 'https://acadiadiv.ca/faculty/'),
	('ENVS', 'Environmental Science', 'https://ees.acadiau.ca/faculty-staff.html'),
	('INCD', 'Indigenous Community Develop.', 'https://commdev.acadiau.ca/faculty-staff.html'),
	('WGST', 'Women''s and Gender Studies', 'https://womenstudies.acadiau.ca/Faculty_Members.html'),
	('ESST', 'Environ. and Sustain. Studies', 'https://environment.acadiau.ca/faculty_staff.html'),
	('HEBR', 'Hebrew', 'https://acadiadiv.ca/faculty/'),
	('SPAN', 'Spanish', 'https://languages.acadiau.ca/faculty-and-staff.html'),
	('CREL', 'Comparative Religion', 'https://history.acadiau.ca/Faculty/Staff.html'),
	('LATI', 'Latin', 'https://history.acadiau.ca/Faculty/Staff.html'),
	('COOP', 'Cooperative Education', 'https://co-op.acadiau.ca/Contact.html'),
	('BIOT', 'Biotechnology', 'https://biology.acadiau.ca/faculty-staff.html'),
	('COMM', 'Communications', 'https://business.acadiau.ca/about-us/faculty-directory.html'),
	('LAWS', 'Law and Society', 'https://laws.acadiau.ca/faculty.html'),
	('ARAM', 'Aramaic', 'https://acadiadiv.ca/faculty/'),
	('GEOM', 'Applied Geomatics', 'https://ees.acadiau.ca/faculty-staff.html'),
	('SOPT', 'Social and Political Thought', 'https://spt.acadiau.ca/spt-faculty.html'),
	('IDTH', 'Interdisciplinary Studies Theo', 'https://acadiadiv.ca/faculty/'),
	('LANG', 'Languages and Literatures', 'https://languages.acadiau.ca/faculty-and-staff.html'),
	('MIKM', 'Mi''kmaw', 'https://education.acadiau.ca/faculty-staff.html')
ON CONFLICT(`prefix`) DO UPDATE SET
	`name` = excluded.`name`,
	`facultyUrl` = excluded.`facultyUrl`;
